/*
 * =========================================================================
 * Project:       RayTrophi Studio
 * File:          FoamSurface.h
 * Author:        Kemal Demirtas
 * License:       MIT
 * =========================================================================
 *
 * Metaball surfacing for whitewater foam.
 *
 * The foam particles (FoamParticles, generated by FluidFoam) are fused into a
 * single smooth implicit surface — a Zhu-Bridson / union-of-spheres level set —
 * and meshed (marching cubes) into a deforming triangle mesh. Unlike the old
 * "Volume" foam (a white scattering NanoVDB that fought the fluid surface volume
 * on the Vulkan integrator), this is REAL geometry: it carries an ordinary scene
 * material and composites correctly on every backend with no volume-coincidence
 * issues. The render bridge wraps the output in a transient InstanceManager group.
 *
 * Built on OpenVDB (already linked): ParticlesToLevelSet rasterises the foam
 * spheres into a narrow-band level set, an optional LevelSetFilter smooths it,
 * and volumeToMesh extracts the iso=0 surface. Output is world-space verts +
 * per-vertex normals + a triangulated index buffer.
 */

#pragma once

#include "../Vec3.h"
#include "../FluidGrid.h"
#include "FluidFoam.h"

#include <vector>
#include <cstdint>

namespace RayTrophiSim {
namespace Fluid {

struct FoamMesh {
    std::vector<Vec3>     positions;   // world space
    std::vector<Vec3>     normals;     // per-vertex, unit
    std::vector<uint32_t> indices;     // triangle list (3 per tri)

    void clear() { positions.clear(); normals.clear(); indices.clear(); }
    bool empty() const { return indices.empty(); }
    std::size_t triangleCount() const { return indices.size() / 3; }
};

// Build a metaball surface mesh from the foam particles. `grid` supplies the
// world placement + voxel size; `params` the SDF radii / smoothing / refinement.
// Returns true and fills `out` when a non-empty surface was produced. The mesh
// is in WORLD space (no instance transform needed). Cheap early-out on empty foam.
bool buildFoamSurface(const FoamParticles& foam,
                      const FluidSim::FluidGrid& grid,
                      const FoamParams& params,
                      FoamMesh& out);

} // namespace Fluid
} // namespace RayTrophiSim
